- desktop.ini
- src/pages/Parents/Allowance/SendAllowancePage.css
- src/pages/Parents/Allowance/SendAllowancePage.jsx
- src/routers/MainRouter.jsx
부모 용돈보내기 UI 구현
* 부모 용돈보내기 UI 구현
* MainRounter 에  path추가
#5
> feat:SendAllowancePage-UI(#5)

- .prettierrc
- package-lock.json
- package.json
> chore : set prettier

- package-lock.json
- package.json
- src/App.jsx
- src/pages/Children/GroupPurchase/Comment.jsx
- src/pages/Children/GroupPurchase/DataSelection.jsx
- src/pages/Children/GroupPurchase/GroupPurchaseDetailPage.jsx
- src/pages/Children/GroupPurchase/GroupPurchaseListPage.jsx
- src/routers/MainRouter.jsx
header 생성 , page
*  header 생성 , page
* 
10
> Feature/10 header 생성 , page

- package-lock.json
- package.json
- src/pages/Parents/Allowance/FixedExpenseListPage.css
- src/pages/Parents/Allowance/FixedExpenseListPage.jsx
- src/pages/Parents/Allowance/SendAllowancePage.jsx
- src/pages/Start/OnboardingPage.jsx
- src/routers/MainRouter.jsx
FixedExpense UI구현
* 부모 고정 지출 UI 구현
#15
> feat:FixedExpenseUI(#15)

- src/components/HistoryItem.jsx
- src/components/UsageHistory.module.css
- src/libs/apis/accounts.js
- src/main.jsx
- src/pages/Children/Usage/UsageHistoryPage.jsx
- src/routers/MainRouter.jsx
- vite.config.js
자녀 잔액 & 이용내역 조회 페이지 작성
* components/historyitem 작성 (후에 부모에서 자녀 이용내역 조회 시 사용)
* components/관련 css 작성 (위와 같음)
* UsageHistoryPage 작성 
#6
> Feat : make children usage page(#6)

- src/components/Header.jsx
header.css -> Header.css 로 경로 수정
> Fix : modify import route in header

- src/pages/Children/GroupPurchase/Comment.jsx
- src/routers/MainRouter.jsx
> 'main router-수정'

- src/pages/Children/Usage/UsageHistoryPage.jsx
history가 없는 예외 case 추가
* history null 여부 확인 추가
> Fix : add exception

- Dockerfile
Dockerfile 작성
* nginx를 통해 react 배포
#51
> Feat : make Dockerfile(#51)

- .github/workflows/deploy.yml
> Feat : make deploy.yml (#51)

- Dockerfile
> Fix : modify nginx route(#51)

- nginx.conf
nginx.conf 파일 추가
* react 라우팅을 위한 nginx.conf 
* 
#51
> Feat : add nginx.conf file

- .github/workflows/deploy.yml
deploy 파일 수정
* deploy.yml 수정
* username 이용하여 dockername 재수정
#51
> Fix : modify deploy.yml(#51)

- .github/workflows/deploy.yml
> fix network(#51)

- src/pages/Parents/Allowance/FixedExpenseListPage.jsx
다른 페이지갔다가 오면 송금하는 amount가 사라지는 문제 localstorage사용해서 해결
*  localstorage사용
#57
> fix:localstorage-amount(#57)

- src/components/Usage/HistoryItem.jsx
- src/libs/apis/histories.js
- src/pages/Children/Usage/HistoryDetailPage.jsx
- src/pages/Children/Usage/UsageHistoryPage.jsx
- src/routers/MainRouter.jsx
각 내역의 정보를 조회하는 페이지를 작성합니다.
* history detail page로 navigate하기 위해 기존 코드들 일부 수정
* historyDetailPage 생성 (tailwindcss 사용)
> Feat : add historyDetailPage(#64)

- src/libs/apis/histories.js
- src/pages/Children/GroupPurchase/Comment.jsx
- src/pages/Children/Usage/PhotoUploadPage.jsx
photo api 와 연결
* comment 에서 useAuth 삭제
* libs/apis에 추가 
#39
> Feat : make connect save photo api(#39)

- src/pages/Children/HomePage.jsx
- src/pages/Children/Usage/HistoryDetailPage.jsx
- src/pages/Children/Usage/UsageHistoryPage.jsx
페이지간 연결
* 각 페이지 navigate 빠져있던 부분들 추가하여 연결
#64
> Feat : connect page with navigate(#64)

- src/pages/Children/Usage/PhotoUploadPage.jsx
> Fix : make upload function(#64)

- src/App.jsx
- src/contexts/AllowanceContext.jsx
- src/pages/Children/Allowance/AllowanceRequestConfirmPage.jsx
- src/pages/Children/Allowance/AllowanceRequestPage.jsx
용돈 조르기 부분 useContext 추가
* 
* 
#73
> fix: add Allowance Context(#73)

- nginx.conf
> modify nginx.conf for filesize

- src/pages/Children/Allowance/AllowanceRequestConfirmPage.jsx
> feat: add AllowanceRequese API(#73)

- src/pages/Children/Allowance/AllowanceComplete.jsx
- src/routers/MainRouter.jsx
> feat:Request Confirm UI(#73)

- src/pages/Children/Allowance/AllowanceRequestConfirmPage.jsx
navigate to complete 추가
* 
* 
#73
> feat: add navigate to complete(#73)

- src/pages/Parents/Allowance/SendAllowancePage.css
- src/pages/Parents/Allowance/SendAllowancePage.jsx
> fix: send allowance design(#85)

- src/components/Usage/HistoryItem.jsx
- src/components/Usage/Usage.module.css
- src/pages/Children/Usage/UsageHistoryPage.jsx
> Feat : add icon when img saved(#64)

- src/components/Usage/HistoryItem.jsx
- src/components/Usage/Usage.module.css
- src/pages/Parents/HomePage.jsx
- src/pages/Parents/Usage/UsageHistoryPage.jsx
부모 메인 - 자녀 이용내역 페이지 연결
* navigate로 페이지간 연결
* 부모는 사진 볼 수 X -> 유저의 role에 따라 아이콘 show 여부, detail 페이지 이동 가능 여부 제한
#34
> Feat : connect page each other with navigate(34)

- src/pages/Parents/HomePage.jsx
> fix: isLoading Debug(#89)

- src/contexts/AuthContext.jsx
- src/pages/Parents/Allowance/FixedExpenseListPage.jsx
- src/pages/Parents/Allowance/SendAllowancePage.jsx
- src/pages/Parents/Allowance/SendCompletePage.jsx
> fix: child context add(#91)

- src/pages/Children/Allowance/AllowanceComplete.jsx
- src/pages/Parents/Allowance/SendCompletePage.jsx
> fix : navigate(#93)

- src/pages/Children/Allowance/AllowanceRequestPage.jsx
> fix : plea slider(#95)

- src/pages/Parents/Allowance/FixedExpenseListPage.jsx
> fix: fixed chart (#99)

- src/pages/Parents/Allowance/AddFixedExpensePage.jsx
- src/pages/Parents/Allowance/FixedExpenseListPage.jsx
고정지출이 송금하려는 금액보다 클 때 안 보내지도록 수정
* 금액 입력창에서 숫자만 입력 되도록 변경
* 고정지출이 송금하려는 금액보다 클 때 안 보내지도록 수정
#105
> fix : add alert(#105)

- package-lock.json
- package.json
- src/pages/Children/GroupPurchase/School.jsx
> Fix : modify school key

- src/pages/Children/Quiz/Quiz.jsx
> fix : answer page (#109)

- src/contexts/AuthContext.jsx
- src/libs/apis/users.js
- src/pages/Start/AuthPage.jsx
- src/pages/Start/SignUpFormPage.jsx
지금 1. 인증하기 (openapi)에서 code 받아오기 완료
2. 토큰 발급받기 (token) 받아오기 완료
#116
> Feat : make update token lips(#116)

- src/pages/Start/AuthPage.jsx
기능 최종 연결
* access  Token 연결
* 
#116
> Fix : update token on user model(#116)

- src/pages/Start/AuthPage.jsx
> fix : authpage (#122)

- src/libs/apis/users.js
- src/pages/Start/AuthPage.jsx
> Feat : update user seq no (#116)

- .github/workflows/deploy.yml
> Fix : modify env route

- Dockerfile
> Fix : modify dockerfile using arg

- src/pages/Start/AuthPage.jsx
토큰 업데이트, 유저 조회, 계좌 생성 api 에러 로직 추가
* AuthPage에서 api 호출 시 try catch로 오류 잡을 수 있도록 수정
#136
> Fix : refactor code using try-catch(#136)

- src/pages/Start/AuthPage.jsx
> Fix: make VITE_URI(#138)

- src/pages/Children/Quiz/Quiz.jsx
> fix: quiz (#142)

- src/pages/Children/Usage/UsageHistoryPage.jsx
> Fix : connect user with useAuth(#148)

- src/pages/Parents/Usage/UsageHistoryPage.jsx
부모 - 자녀 이용내역 조회 연결
* authContext로 자녀 연결
#148
> Fix : connect child with useAuth(#148)

- vite.config.js
프록시 경로 충돌 해결
* proxy route에 oauth 제거
* 
#148
> Fix : modify proxy route(#148)

- src/libs/apis/users.js
- src/pages/Children/Allowance/AllowanceRequestConfirmPage.jsx
- src/pages/Children/HomePage.jsx
- src/routers/ProtectedRoute.jsx
plea parent name 추가
* useEffect로 get api가져오기 
* userData를 저장하는 state 만들어서 부모이름 띄우기 
#147
> fix : plea parent name (#147)

- src/pages/Start/AuthPage.jsx
front에서 직접 호출 -> backend 통해서 호출하도록 로직 수정
* 기존 호출 로직 삭제 및 api 호출
#116
> Fix : make openbank api in express for using in react

- src/libs/apis/users.js
user  정보 조회도 express를 통해서 요청 갈 수 있도록 수정
* user 정보 조회 
#116
> Fix : modify fetch User(#116)

- src/libs/apis/tip.js
- src/pages/Parents/Allowance/Tip/Tip.jsx
- src/pages/Parents/HomePage.jsx
- src/routers/MainRouter.jsx
> feat: tip ui (#156)

- src/libs/apis/accounts.js
- src/pages/Parents/HomePage.jsx
- src/pages/Start/AuthPage.jsx
open account 연결
* 부모 페이지 - 가상 계좌 연결
#162
> Feat : get open account info(#162)

- src/pages/Children/HomePage.jsx
- src/pages/Parents/HomePage.jsx
아이 메인 페이지에서 open account 연결
* 가상 계좌 번호 연결
#162
> Feat : get open account in children home(#162)

- src/pages/Children/Quiz/Quiz.jsx
> Fix : quiz (#168)

- src/pages/Children/HomePage.jsx
> Fix : add catch error code (#162)

- src/pages/Children/HomePage.jsx
- src/pages/Parents/HomePage.jsx
계좌번호 계좌에서 불러오게 수정
* 부모/자녀 메인 페이지 계좌번호 조회 수정
#162
> Fix : get account num from db(#162)

- src/pages/Children/HomePage.jsx
> Fix : modify number to num(#162)

- src/pages/Children/HomePage.jsx
- src/pages/Parents/NotifiactionPage.jsx
- src/pages/Start/AuthPage.jsx
> Feat/160 websocket-2

- src/libs/apis/quiz.js
- src/pages/Children/Quiz/Quiz.jsx
> fix : quiz api (#174)

- src/pages/Parents/Allowance/FixedExpenseListPage.jsx
> Fix : add parent_id with reqeust Body

- src/pages/Parents/Allowance/FixedExpenseListPage.jsx
고정 지출 차트를 원래 입력한 전체 금액 대비 고정 지출 비율로 나타나도록 수정함
* 차트 내용 수정
* 계산 식 수정
#180
> fix : chart (#180)

- src/pages/Parents/Allowance/SendAllowancePage.jsx
계좌 잔액 띄우는 거 추가
* 잔액조회 api연결해서 계좌 잔액 띄우는 거 추가 
#182
> fix : balance (#182)

- src/pages/Children/HomePage.jsx
- src/pages/Parents/HomePage.jsx
숫자 3자리마다 콤마추가 
* localeString활용하여 콤마추가 
#184
> fix : locale (#184)

- src/pages/Parents/HomePage.jsx
부모 메인페이지 수정
* 자녀 선택할 시에만 잔액 뜨도록
#24
> Fix : modify get child balance according to child presence

- src/pages/Parents/HomePage.jsx
자녀 잔액 0일때 처리
* 자녀 잔액이 0인 경우 처리
#24
> Fix : add case localeAmount 0

- src/pages/Children/Usage/HistoryDetailPage.jsx
usage photo upload navigate 추가
* 기존 사진을 추가하세요만 네비게이트 -> 빈 사진도 누르면 이동하도록 수정
#191
> Fix : modify add navigate to photo upload(#191)

- src/pages/Parents/HomePage.jsx
자녀 선택시 홈화면 리렌더링 현상을 해결합니다.
* useEffect dependency array애서 selectChild 함수 제거
#191
> Fix : remove setchild in dependency array(#191)

- src/pages/Parents/HomePage.jsx
자녀 잔액 비동기 처리
* 비동기 state 값 비교 처리
* 로직 처리 과정에 state로 로딩중.. 추가
#191
> Fix : modify get child balance in parents' page(#191)

- src/pages/Children/Quiz/Quiz.jsx
> Fix: quiz layout(#196)

- src/pages/Parents/Allowance/AddFixedExpensePage.jsx
> fix : alert scheduled (#198)

- src/libs/apis/accounts.js
- src/pages/Parents/Allowance/FixedExpenseListPage.jsx
> refac : send api(#207)

- nginx.conf
* ssl certificate 적용을 위한 nginx 수정
#191
> Fix : test nginx.conf for ssl

- src/pages/Children/Quiz/Quiz.jsx
> refac : quiz (#211)

- nginx.conf
> Fix : modify certbot route(#191)

- nginx.conf
> Fix : modify temp nginx for get certificate(#191)

- src/pages/Parents/Allowance/AddFixedExpensePage.jsx
- src/pages/Parents/Allowance/FixedExpenseListPage.jsx
고정금액 합한게 , 입력한 금액 보다 더 크면 안되게 수정
* 
* 
#220
> refac : fixed amount (#220)

- nginx.conf
> Fix : modify domain

- src/components/Header.jsx
- src/contexts/NotificationContext.jsx
- src/pages/Children/HomePage.jsx
- src/pages/Parents/NotifiactionPage.jsx
완료~!~!~!~!~!~!~!~!~!~!~!~ 
* 
*
> 'conflict-resolve'

- src/pages/Parents/Allowance/FixedExpenseListPage.jsx
> fix : chart (#232)

- src/pages/Children/Quiz/Quiz.jsx
button flex 속성 추가해서 중앙정렬 
* 
*
> refac : button flex (#234)

- src/pages/Parents/Usage/UsageHistoryPage.jsx
부모 - 자녀 이용내역 조회 페이지 새고 오류 해결
* state 있으면 state로 없으면 localstorage에서 불러오도록 수정 
#191
> Fix : modify load child's balacne in parents using localstorage(#191)

- src/pages/Parents/Allowance/SendAllowancePage.jsx
용돈 송금 가능 금액 수정
* 잔액 초과 입력 안됨
#191
> Fix : modify allowance amount(#191)

- src/pages/Children/GroupPurchase/GroupPurchaseReg.jsx
- src/pages/Children/NotificationPage.jsx
- src/pages/Parents/NotifiactionPage.jsx
> refac : add placeholder(#243)

- nginx.conf
- src/libs/apis/sockets.js
> Fix : modify nginx & add socket.js for web-socket(#191)
